samples_file:
    "code/snakemake/20210203/config/samples.csv"
target_dir:
    "../introgression/release-102"
sing_cont_r:
    "../sing_conts/baseR.sif"
conda_r:
    "envs/baseR.yaml"    
segments_script:
    "code/scripts/introgression/20200907_extract-emf-segments.sh"
add_coord_script_forward:
    "code/scripts/introgression/20200908_add-hdrr-coords-to-emf-data.R"
add_coord_script_reverse:
    "code/scripts/introgression/20201015_add-hdrr-coords-to-emf-data_rc.R"
consol_subchr_script:
    "code/scripts/introgression/20201015_consolidate_chr_dat.R"
consol_chr_script:
    "code/scripts/introgression/20201015_consolidate_chr_files.R"
vcf_dir:
    "../introgression/vcfs"
mikk_ill_vcf:
    "/nfs/research1/birney/projects/medaka/inbred_panel/medaka-alignments-release-94/vcf/medaka_inbred_panel_ensembl_new_reference_release_94.vcf"
bcftools:
    "../sing_conts/bcftools.sif"
no_sibs_cramid:
    "data/20200227_cram2line_no-sibs_cram-only.txt"    
cramid_2_lineid_key:
    "data/20200206_cram_id_to_line_id.txt"
no_sibs_lineid:
    "data/20200914_samples_no-sibs.txt"
split_mikk_file_script:
    "scripts/20210315_split_mikk_file.R"
maf_dir:
    "../introgression/mafs"
freq_tables_dir:
    "../introgression/freq_tables"
combine_emf_maf_script:
    "code/scripts/introgression/20210315_combine_final_and_af_data.R"
combine_chr_freq_tables_script:
    "code/scripts/introgression/20210315_combine_chr_freq_tables.R"
combine_all_mikk_freq_tables_script:
    "code/scripts/introgression/20210315_combine_all_mikk_freq_tables.R"
abba_baba_dir:
    "../introgression/abba_baba"    
abba_baba_script:
    "code/scripts/introgression/run_abbababa.R"
combine_rlists_script:
    "code/scripts/introgression/combine_rlists.R"


